### ISSUE TITLE
Deprecated positional argument(s) used in SFTTrainer

### ISSUE THREAD

**Issue by JinYu1998** [arcee-ai/DistillKit#10]
When I run `accelerate launch distil_logits.py`, I get the following error.  ( I'm using a 40G A100 from Colab.

```
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
2024-09-01 11:07:10.764922: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-09-01 11:07:10.782866: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-01 11:07:10.804033: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-01 11:07:10.810503: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-09-01 11:07:10.826006: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-09-01 11:07:11.993337: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-09-01 11:07:13,523] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Preprocessing and tokenizing dataset...
Dataset preparation complete. Loading models...
You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
Loading checkpoint shards: 100% 4/4 [00:10<00:00,  2.70s/it]
Spectrum configuration not found. All layers of the student model will be trainable.
/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_deprecation.py:100: FutureWarning: Deprecated argument(s) used in '__init__': max_seq_length. Will not be supported from version '1.0.0'.

Deprecated positional argument(s) used in SFTTrainer, please use the SFTConfig to set these arguments instead.
  warnings.warn(message, FutureWarning)
/usr/local/lib/python3.10/dist-packages/trl/trainer/sft_trainer.py:283: UserWarning: You passed a `max_seq_length` argument to the SFTTrainer, the value you passed will override the one in the `SFTConfig`.
  warnings.warn(
Traceback (most recent call last):
  File "/content/DistillKit/distil_logits.py", line 171, in <module>
    trainer = LogitsTrainer(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/trl/trainer/sft_trainer.py", line 350, in __init__
    raise ValueError(
ValueError: You passed `packing=False` to the SFTTrainer/SFTConfig, but you didn't pass a `dataset_text_field` or `formatting_func` argument.
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1097, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 703, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'distil_logits.py']' returned non-zero exit status 1.
```

How should I solve this problem please ?

**Comment by tusg** [comment]
`Spectrum configuration not found. All layers of the student model will be trainable.
/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_deprecation.py:100: FutureWarning: Deprecated argument(s) used in '__init__': max_seq_length. Will not be supported from version '1.0.0'.

Deprecated positional argument(s) used in SFTTrainer, please use the SFTConfig to set these arguments instead.
  warnings.warn(message, FutureWarning)
/opt/conda/lib/python3.10/site-packages/trl/trainer/sft_trainer.py:283: UserWarning: You passed a `max_seq_length` argument to the SFTTrainer, the value you passed will override the one in the `SFTConfig`.
  warnings.warn(
Traceback (most recent call last):
  File "/home/jupyter/DistillKit/distil_logits.py", line 171, in <module>
    trainer = LogitsTrainer(
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 350, in __init__
    raise ValueError(
ValueError: You passed `packing=False` to the SFTTrainer/SFTConfig, but you didn't pass a `dataset_text_field` or `formatting_func` argument.
Traceback (most recent call last):
  File "/opt/conda/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1106, in launch_command
    simple_launcher(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 704, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python3.10', 'distil_logits.py']' returned non-zero exit status 1.`

Even I am facing the same issue, I am using 1 L4.

**Comment by JinYu1998** [comment]
@tusg  I still haven't solved the problem. Very excited to see how my distillation algorithm works on LLM. But now I'm stuck with this bug ....

**Comment by noob-coderx** [comment]
I an going through the same problem, but haven't figured out a solution so far

**Comment by Crystalcareai** [comment]
Apologies - been a bit distracted with some lab work. I'll take a look at this tomorrow.

**Comment by JinYu1998** [comment]
> Apologies - been a bit distracted with some lab work. I'll take a look at this tomorrow.

I wonder if there has been any progress on the error we discussed earlier? I really appreciate your time and effort!

**Comment by louyuanyuan053709** [comment]
refer to this link: https://stackoverflow.com/questions/77113551/trl-sfttrainer-llama2-finetuning-on-alpaca-datasettext-field

**Comment by Crystalcareai** [comment]
This should be fixed in the short term - I'll be locking some of the dependencies in the coming days.

**Comment by Wolfman1219** [comment]
Can anyone solve this problem?
