### ISSUE TITLE
Distillation with distil_hidden.py when launched fails with Pytorch Version 2.4 with "_get_socket_with_port"

### ISSUE THREAD

**Issue by Nottlespike** [arcee-ai/DistillKit#2]
So I am having this issue with mutli GPU distillation when using accelerate config to either FDSP or Deepspeed all configs with the same  error of `ImportError: cannot import name '_get_socket_with_port' from 'torch.distributed.elastic.agent.server.api' (/home/kearm/miniconda3/lib/python3.11/site-packages/torch/distributed/elastic/agent/server/api.py)` with varying levels of verbosity depending on the exact config I setup with `accelerate config` to then use `accelerate launch distil_hidden.py` My suspicion is that I am using too new of a Pytorch version of 2.4. Is there a recommended or tested Pytorch version or is it more likely I failed to do the setup properly?

**Comment by Nottlespike** [comment]
Ok upon further testing with a smaller model even single GPU distil_hidden.py fails with this full traceback:
python distil_hidden.py
```
[2024-08-01 23:36:10,508] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.4
 [WARNING]  using untested triton version (3.0.0), only 1.0.0 is known to be compatible
/home/kearm/miniconda3/lib/python3.11/site-packages/deepspeed/runtime/zero/linear.py:47: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @autocast_custom_fwd
/home/kearm/miniconda3/lib/python3.11/site-packages/deepspeed/runtime/zero/linear.py:66: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @autocast_custom_bwd
Traceback (most recent call last):
  File "/home/kearm/miniconda3/lib/python3.11/site-packages/trl/import_utils.py", line 180, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kearm/miniconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kearm/miniconda3/lib/python3.11/site-packages/trl/trainer/sft_trainer.py", line 41, in <module>
    from ..extras.dataset_formatting import get_formatting_func_from_dataset
  File "/home/kearm/miniconda3/lib/python3.11/site-packages/trl/extras/dataset_formatting.py", line 7, in <module>
    from ..trainer.utils import ConstantLengthDataset
  File "/home/kearm/miniconda3/lib/python3.11/site-packages/trl/trainer/utils.py", line 51, in <module>
    import deepspeed
  File "/home/kearm/miniconda3/lib/python3.11/site-packages/deepspeed/__init__.py", line 26, in <module>
    from . import module_inject
  File "/home/kearm/miniconda3/lib/python3.11/site-packages/deepspeed/module_inject/__init__.py", line 6, in <module>
    from .replace_module import replace_transformer_layer, revert_transformer_layer, ReplaceWithTensorSlicing, GroupQuantizer, generic_injection
  File "/home/kearm/miniconda3/lib/python3.11/site-packages/deepspeed/module_inject/replace_module.py", line 607, in <module>
    from ..pipe import PipelineModule
  File "/home/kearm/miniconda3/lib/python3.11/site-packages/deepspeed/pipe/__init__.py", line 6, in <module>
    from ..runtime.pipe import PipelineModule, LayerSpec, TiedLayerSpec
  File "/home/kearm/miniconda3/lib/python3.11/site-packages/deepspeed/runtime/pipe/__init__.py", line 6, in <module>
    from .module import PipelineModule, LayerSpec, TiedLayerSpec
  File "/home/kearm/miniconda3/lib/python3.11/site-packages/deepspeed/runtime/pipe/module.py", line 19, in <module>
    from ..activation_checkpointing import checkpointing
  File "/home/kearm/miniconda3/lib/python3.11/site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 26, in <module>
    from deepspeed.runtime.config import DeepSpeedConfig
  File "/home/kearm/miniconda3/lib/python3.11/site-packages/deepspeed/runtime/config.py", line 42, in <module>
    from ..elasticity import (
  File "/home/kearm/miniconda3/lib/python3.11/site-packages/deepspeed/elasticity/__init__.py", line 10, in <module>
    from .elastic_agent import DSElasticAgent
  File "/home/kearm/miniconda3/lib/python3.11/site-packages/deepspeed/elasticity/elastic_agent.py", line 9, in <module>
    from torch.distributed.elastic.agent.server.api import _get_socket_with_port
ImportError: cannot import name '_get_socket_with_port' from 'torch.distributed.elastic.agent.server.api' (/home/kearm/miniconda3/lib/python3.11/site-packages/torch/distributed/elastic/agent/server/api.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kearm/DistillKit/distil_hidden.py", line 5, in <module>
    from trl import SFTTrainer
  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
  File "/home/kearm/miniconda3/lib/python3.11/site-packages/trl/import_utils.py", line 171, in __getattr__
    value = getattr(module, name)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kearm/miniconda3/lib/python3.11/site-packages/trl/import_utils.py", line 170, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kearm/miniconda3/lib/python3.11/site-packages/trl/import_utils.py", line 182, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import trl.trainer.sft_trainer because of the following error (look up to see its traceback):
cannot import name '_get_socket_with_port' from 'torch.distributed.elastic.agent.server.api' (/home/kearm/miniconda3/lib/python3.11/site-packages/torch/distributed/elastic/agent/server/api.py)
```

**Comment by Nottlespike** [comment]
From some further testing I eventually got it runningish on Torch 2.0.1 and without Flash-Attn. Is there a known or suggested version of all the dependencies as simply running the setup.sh will pull the most recent versions of all the dependencies and as such it wasn't working for me.

**Comment by Crystalcareai** [comment]
Which models were these?

**Comment by Crystalcareai** [comment]
2.4.0 has worked for me - are you running deepspeed at all?

**Comment by Crystalcareai** [comment]
Fix incoming
